### ISSUE TITLE
Wire vue routes

### ISSUE THREAD

**Issue by jinncoder** [poerhiza/montage#4]
Create basic pages for entire app. workflow - no data, just wiring.

- Add image dialog
- Create gallary dialog
- Gallary viewer
- Un-organized images viewer
- Image searchbar
- Page navigation

**Comment by poerhiza** [comment]
![montage 2](https://user-images.githubusercontent.com/6900588/38534096-e4e5f780-3c41-11e8-82cb-b751e787ddf4.png)
